title: AnimeHub
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Optional: Mermaid, Callouts etc.
mermaid:
  version: '10.5.0'
callouts:
  tip:
    title: ğŸ¤ Tip
    color: purple
  info:
    title: â„¹ï¸ Info
    color: blue
  attention:
    title: â• Attention
    color: yellow
  download:
    title: ğŸ’¾ Download
    color: grey-dk
